- name: Install NVIDIA Drivers
  dnf:
    name:
      - "akmod-nvidia"
      - "vulkan"
    state: present
  become: true

- name: Blacklist the nouveau driver module
  community.general.kernel_blacklist:
    name: nouveau
    state: present
