- name: Get latest release
  community.general.github_release:
    action: latest_release
    user: YS-L
    repo: csvlens
    token: "{{ github_token }}"
  register: release

- name: Download
  ansible.builtin.unarchive:
    dest: "{{ setup_dir }}"
    remote_src: true
    src: https://github.com/YS-L/csvlens/releases/download/{{ release.tag }}/csvlens-x86_64-unknown-linux-gnu.tar.xz
  become: true

- name: Install
  ansible.builtin.copy:
    src: "{{ setup_dir }}/csvlens-x86_64-unknown-linux-gnu/csvlens"
    dest: "{{ bin_dir }}/csvlens"
    mode: a+x
  become: true
