tls:
  # stores:
  #   default:
  #     defaultCertificate:
  #       certFile: "/etc/certs/_wildcard.docker.pem"
  #       keyFile: "/etc/traefcerts/_wildcard.docker-key.pem"
  certificates:
    - certFile: "/etc/certs/_wildcard.docker.pem"
      keyFile: "/etc/certs/_wildcard.docker-key.pem"

    - certFile: "/etc/certs/traefik.docker.pem"
      keyFile: "/etc/certs/traefik.docker-key.pem"

    - certFile: "/etc/certs/portainer.docker.pem"
      keyFile: "/etc/certs/portainer.docker-key.pem"
