- name: Settings | Gedit
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/gedit/preferences/editor/bracket-matching",
        value: "true",
      }
    - { key: "/org/gnome/gedit/preferences/editor/auto-indent", value: "true" }
    - {
        key: "/org/gnome/gedit/preferences/editor/create-backup-copy",
        value: "false",
      }
    - {
        key: "/org/gnome/gedit/preferences/editor/display-line-numbers",
        value: "true",
      }
    - {
        key: "/org/gnome/gedit/preferences/editor/editor-font",
        value: "'Fira Code Light 12'",
      }
    - {
        key: "/org/gnome/gedit/preferences/editor/use-default-font",
        value: "false",
      }
    - { key: "/org/gnome/gedit/preferences/editor/tabs-size", value: 4 }
    - { key: "/org/gnome/gedit/preferences/editor/scheme", value: "'cobalt'" }
