- name: Distrobox
  ansible.builtin.dnf:
    name: distrobox
    state: present
  become: true

- name: DistroShelf
  community.general.flatpak:
    name: com.ranfdev.DistroShelf
    state: present
  become: true
