- ansible.builtin.yum_repository:
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    description: Google Cloud SDK
    enabled: true
    gpgcheck: true
    gpgkey:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    name: google-cloud-sdk
  become: true
  name: Google Cloud SDK | Add Repository
- ansible.builtin.dnf:
    name: google-cloud-sdk
  become: true
  name: Google Cloud SDK | Install
