- name: Install core system packages
  ansible.builtin.dnf:
    name:
      - curl
      - wget
      - unzip
      - python-psutil
      - dconf-editor
      - dnf-plugins-core
      - make
      - pwgen
      - lnav
      - httpie
      - htop
      - iotop
      - ncdu
      - tree
      - figlet
    state: present
  become: true
