# GIMP is an acronym for GNU Image Manipulation Program.
# It is a freely distributed program for such tasks as photo retouching, image composition and image authoring.

- name: Gimp
  flatpak:
    name: org.gimp.GIMP
    state: present
