- name: Youtube DL | Get latest version from GitHub
  github_release:
    user: yt-dlp
    repo: yt-dlp
    action: latest_release
    token: "{{ github_token }}"
  register: ytdlp_release

- name: Youtube DL | Download
  get_url:
    url: https://github.com/yt-dlp/yt-dlp/releases/download/{{ ytdlp_release.tag }}/yt-dlp_linux
    dest: "{{ bin_dir }}/yt-dlp"
    mode: a+x
  become: true
