- name: Java
  dnf:
    name: java-11-openjdk
    state: present
  become: true

- name: Java | Set the correct version
  alternatives:
    name: java
     link: /usr/bin/java
    path: /usr/lib/jvm/java-11-openjdk-11.0.6.10-0.fc32.x86_64/bin/java
  become: true
