- name: Goreleaser | Get latest release
  github_release:
    user: goreleaser
    repo: goreleaser
    action: latest_release
    token: "{{ github_token }}"
  register: release

- name: Goreleaser
  dnf:
    name: https://github.com/goreleaser/goreleaser/releases/download/{{ release.tag }}/goreleaser-{{ release.tag[1:] }}.x86_64.rpm
    state: present
    disable_gpg_check: yes
  become: true
