- name: Rust | check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Rust | Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"

- name: Rust | Install
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
