- name: ZSH | Install
  ansible.builtin.dnf:
    name:
      - zsh
      - util-linux-user
      - powerline-fonts
    state: present
  become: true

- name: ZSH | Set as default shell
  ansible.builtin.shell: chsh -s $(which zsh ) {{ user }}
