- ansible.builtin.file:
    mode: '"0755"'
    path: /etc/loki
    state: directory
  become: true
  name: Loki | Ensure Configuration folder exists
- ansible.builtin.template:
    dest: /etc/loki/config.yaml
    mode: '0644'
    src: loki/loki-local-config.yaml.j2
  become: true
  name: Loki | Ensure Configuration file exists
- community.docker.docker_volume:
    name: loki-storage
    state: present
  name: Loki | Ensure data volume exists
- community.docker.docker_container:
    command: -config.file=/etc/loki/config.yaml
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 10s
      test:
      - CMD
      - wget
      - -qO-
      - http://localhost:3100/ready
      timeout: 2s
    image: grafana/loki:2.8.4
    labels:
      traefik.enable: 'false'
    name: loki
    networks:
    - name: monitoring
    restart_policy: unless-stopped
    state: started
    volumes:
    - /etc/loki/config.yaml:/etc/loki/config.yaml
    - loki-storage:/loki
  name: Loki | Start container
