- name: cAdvisor | Start container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    command: --docker_only=true
    state: started
    restart_policy: "unless-stopped"
    networks:
      - name: monitoring
      - name: traefik-public
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      traefik.enable: "false"

