- name: Docker | Ensure Portainer volume is present
  community.docker.docker_volume:
    name: portainer_data
    state: present

- name: Docker | Start Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:2.18.4-alpine
    restart_policy: "unless-stopped"
    networks:
      - name: traefik-public
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`portainer.docker`)"
      traefik.http.routers.portainer.tls: "true"
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9000/api/status"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
