
- name: Promtail | Create Configuration folder
  ansible.builtin.template:
    src: promtail/promtail-local-config.yml.j2
    dest: /etc/promtail/promtail-local-config.yml
  become: true

- name: Promtail | Start container
  community.docker.docker_container:
    name: promtail
    image: grafana/promtail:2.8.4
    restart_policy: "unless-stopped"
    state: started
    networks:
      - name: monitoring
    labels:
      traefik.enable: "false"
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /etc/promtail/promtail-local-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro # System logs
      - /var/log/journal:/var/log/journal:ro # Journalctl logs
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker container logs
